In [1]:
#Import dependencies

from sklearn import tree
from sklearn.ensemble import RandomForestClassifier

import pandas as pd

import warnings
warnings.simplefilter('ignore')

In [2]:
full_df = pd.read_csv('full_stats')

In [11]:
top_7 = full_df[['opptAST', 'teamAST/TO','teamAST', 'teamPF', 'opptPF', 'teamTO%']]

In [12]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

X = top_7
y = full_df['teamRslt']

label_encoder.fit(y)
y_encoded = label_encoder.transform(y)
y_encoded

array([0, 1, 0, ..., 1, 0, 1], dtype=int64)

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, random_state=42)

In [14]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier

classifier.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [15]:
print(f"Training Data Score: {classifier.score(X_train, y_train)}")
print(f"Testing Data Score: {classifier.score(X_test, y_test)}")

Training Data Score: 0.7440368630285508
Testing Data Score: 0.7430894308943089

In [16]:
predictions = classifier.predict(X_test)
pd.DataFrame({"Prediction": predictions, "Actual": y_test})

      Prediction  Actual
0              0       0
1              1       1
2              0       0
3              1       1
4              0       1
5              0       0
6              1       1
7              0       0
8              1       0
9              0       1
10             0       0
11             0       1
12             1       0
13             0       0
14             0       0
15             0       0
16             1       1
17             0       0
18             0       1
19             1       1
20             0       0
21             1       1
22             1       1
23             0       1
24             1       1
25             1       1
26             0       0
27             0       0
28             0       0
29             0       0
...          ...     ...
3660           0       0
3661           0       0
3662           0       1
3663           1       1
3664           0       0
3665           1       1
3666           1       1
3667           0       1
3668           1       1
3669           0       0
3670           1       1
3671           1       1
3672           0       0
3673           1       1
3674           0       1
3675           1       1
3676           0       0
3677           0       0
3678           0       0
3679           0       1
3680           1       1
3681           1       1
3682           0       0
3683           1       0
3684           0       1
3685           0       0
3686           1       1
3687           1       1
3688           0       0
3689           1       0

[3690 rows x 2 columns]